apiVersion: v1
kind: Service
metadata:
  name: front-app
spec:
  type: LoadBalancer
  selector:
    app: front-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 3016